# Generated by Django 5.2.17 on 2026-09-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_choice_quiz_question_quiz_quizattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Qiimaha koorsada USD (0 = Bilaash)', max_digits=8),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(choices=[('Zaad', 'Telesom Zaad'), ('e-Dahab', 'Dahabshiil e-Dahab'), ('EVC Plus', 'Hormuud EVC Plus'), ('Free', 'Bilaash (Free Enrollment)'), ('Manual', 'Gacanta (Manual Admin)')], default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('approved', 'Fasaxan (Approved)'), ('pending', 'Sugitaan (Pending Approval)'), ('rejected', 'La Diiday (Rejected)')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Casharkan ma u furan yahay arday kasta (Free Preview)?'),
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='courses.lessoncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_resources/')),
                ('url', models.URLField(blank=True, help_text='External resource link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
        ),
    ]
